define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Gem position",
        "titleText": "Titel (obligatorisk)",
        "description": "Beskrivelse",
        "tags": "Nøgleord (obligatorisk)",
        "preview": "Eksempel",
        "submit": "Gem",
        "cancel": "Annuller",
        "pixel": "Pixelstørrelse",
        "outsr": "Output-spatial reference",
        "renderer": "TIFF-downloadindstillinger",
        "formatText1": "Som vist",
        "formatText2": "Rå data (alle bånd)",
        "extent": "Tegn polygon for at definere udstrækning",
        "drawText": "(klik på billede for at starte)",
        "text": "De rå data kan ikke vises med standard-fotovisningsprogrammer. Åbn med ArcGIS Pro.",
        "error": "Ingen synlige billedlag på kortet.",
        "error1": "Titel er påkrævet.",
        "error2": "Nøgleord er påkrævet.",
        "error3": "Pixelstørrelsen på eksporten er begrænset til",
        "error4": "for denne udstrækning",
        "error5": "Angiv en gyldig numerisk værdi.",
        "error6": "Dit billede kan ikke eksporteres på nuværende tidspunkt.",
        "thumbnailError": "Intet miniaturebillede er tilgængeligt",
        "advance": "Avancerede lagringsindstillinger",
        "modeOption1": "Gem på portal",
        "modeOption2": "Gem på disk",
        "default": "Standard",
        "utm": "WGS84 UTM zone",
        "layer": "Lag",
        "mercator": "WebMercatorAS",
        "folder": "Vælg mappe"
    })
});