define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Desa la ubicació",
        "titleText": "Títol (necessari)",
        "description": "Descripció",
        "tags": "Etiquetes (necessàries)",
        "preview": "Visualització prèvia",
        "submit": "Desa",
        "cancel": "Cancel·la",
        "pixel": "Mida de píxel",
        "outsr": "Referència espacial de sortida",
        "renderer": "Opcions de baixada de fitxers TIFF",
        "formatText1": "Tal com es mostra",
        "formatText2": "Dades sense format (totes les bandes)",
        "extent": "Dibuixa un polígon per definir l'extensió",
        "drawText": "(feu clic a la imatge per començar)",
        "text": "Les dades sense format no es poden mostrar amb visors de fotografies estàndard. Obriu-ho amb l'ArcGIS Pro.",
        "error": "No hi ha cap capa d'imatges visible al mapa.",
        "error1": "El títol és necessari.",
        "error2": "Les etiquetes són necessàries.",
        "error3": "El valor de Mida de píxel de l'exportació es limita a",
        "error4": "per a aquesta extensió.",
        "error5": "Introduïu un valor numèric vàlid.",
        "error6": "La imatge no es pot exportar en aquest moment.",
        "thumbnailError": "No hi ha cap miniatura disponible",
        "advance": "Opcions de desament avançades",
        "modeOption1": "Desa-ho al portal",
        "modeOption2": "Desa-ho al disc",
        "default": "Per defecte",
        "utm": "Zona UTM del WGS84",
        "layer": "Capa",
        "mercator": "WebMercatorAS",
        "folder": "Seleccioneu la carpeta"
    })
});