define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Lưu vị trí",
        "titleText": "Tiêu đề (bắt buộc)",
        "description": "Mô tả",
        "tags": "Thẻ (bắt buộc)",
        "preview": "Xem trước",
        "submit": "Lưu",
        "cancel": "Hủy",
        "pixel": "Kích thước Pixel",
        "outsr": "Tham chiếu Không gian Đầu ra",
        "renderer": "Tùy chọn tải về TIFF",
        "formatText1": "Như hiển thị",
        "formatText2": "Dữ liệu thô (tất cả các dải sóng)",
        "extent": "Vẽ đa giác để xác định phạm vi",
        "drawText": "(bấm vào hình ảnh để bắt đầu)",
        "text": "Không thể hiển thị dữ liệu thô bằng chương trình xem ảnh thông thường. Vui lòng mở bằng ArcGIS Pro.",
        "error": "Không có lớp hình ảnh nào hiển thị trên bản đồ.",
        "error1": "Cần có tiêu đề.",
        "error2": "Cần có (các) Thẻ.",
        "error3": "Kích thước pixel của nội dung xuất ra được giới hạn đến",
        "error4": "cho phạm vi này.",
        "error5": "Vui lòng nhập giá trị số hợp lệ.",
        "error6": "Không thể xuất hình ảnh của bạn lúc này.",
        "thumbnailError": "Không có hình thu nhỏ",
        "advance": "Tùy chọn lưu nâng cao",
        "modeOption1": "Lưu vào cổng thông tin",
        "modeOption2": "Lưu vào ổ đĩa",
        "default": "Mặc định",
        "utm": "Khu vực UTM WGS84",
        "layer": "Lớp",
        "mercator": "WebMercatorAS",
        "folder": "Chọn thư mục"
    })
});