define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "位置の保存",
        "titleText": "タイトル (必須)",
        "description": "説明",
        "tags": "タグ (必須)",
        "preview": "プレビュー",
        "submit": "保存",
        "cancel": "キャンセル",
        "pixel": "ピクセル サイズ",
        "outsr": "出力データの空間参照",
        "renderer": "TIFF ダウンロード オプション",
        "formatText1": "表示",
        "formatText2": "未処理データ (すべてのバンド)",
        "extent": "ポリゴンを描画して範囲を定義",
        "drawText": "(画像をクリックすると開始します)",
        "text": "標準の写真ビューアーを使用して未処理データを表示することはできません。 ArcGIS Pro で開きます。",
        "error": "マップに表示可能なイメージ レイヤーがありません。",
        "error1": "タイトルの指定が必須です。",
        "error2": "タグが必要です。",
        "error3": "この範囲の場合、エクスポートのピクセルサイズは、",
        "error4": "に制限されます。",
        "error5": "有効な数値を入力してください。",
        "error6": "この時点で画像をエクスポートすることはできません。",
        "thumbnailError": "利用可能なサムネイルがありません",
        "advance": "高度な保存オプション",
        "modeOption1": "ポータルに保存",
        "modeOption2": "ディスクに保存",
        "default": "既定",
        "utm": "WGS84 UTM ゾーン",
        "layer": "レイヤー",
        "mercator": "WebMercatorAS",
        "folder": "フォルダー選択"
    })
});