define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Hely mentése",
        "titleText": "Cím (kötelező)",
        "description": "Leírás",
        "tags": "Címkék (kötelező)",
        "preview": "Előnézet",
        "submit": "Mentés",
        "cancel": "Mégse",
        "pixel": "Képpontméret",
        "outsr": "Kimeneti koordináta-rendszer",
        "renderer": "TIFF-letöltési beállítások",
        "formatText1": "Ahogy megjelenik",
        "formatText2": "Nyers adat (összes sáv)",
        "extent": "Polygon rajzolása kiterjedés meghatározására",
        "drawText": "(az indításhoz kattintson a képre)",
        "text": "A nyers adat nem jeleníthető meg szabványos fényképmegtekintővel. Megnyitás ArcGIS Pro-val.",
        "error": "Nincsenek látható távérzékelési rétegek a térképen.",
        "error1": "A címet meg kell adni.",
        "error2": "A címké(ke)t meg kell adni.",
        "error3": "Az export pixelmérete korlátozva:",
        "error4": "ehhez a kiterjedéshez.",
        "error5": "Érvényes numerikus értéket adjon meg",
        "error6": "A képe jelenleg nem exportálható.",
        "thumbnailError": "Bélyegkép nem áll rendelkezésre",
        "advance": "Speciális mentési beállítások",
        "modeOption1": "Mentés portálra",
        "modeOption2": "Mentés lemezre",
        "default": "Alapértelmezett",
        "utm": "WGS84 UTM zóna",
        "layer": "Réteg",
        "mercator": "WebMercatorAS",
        "folder": "Válassza ki a mappát"
    })
});