define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "위치 저장",
        "titleText": "제목(필수)",
        "description": "설명",
        "tags": "태그(필수)",
        "preview": "미리 보기",
        "submit": "저장",
        "cancel": "취소",
        "pixel": "픽셀 크기",
        "outsr": "결과 공간 참조",
        "renderer": "TIFF 다운로드 옵션",
        "formatText1": "표시된 대로",
        "formatText2": "원시 데이터(모든 밴드)",
        "extent": "폴리곤을 그려 범위 정의",
        "drawText": "(시작할 이미지 클릭)",
        "text": "표준 사진 뷰어를 사용하여 원시 데이터를 표시할 수 없습니다. ArcGIS Pro로 엽니다.",
        "error": "맵에 보이는 이미지 레이어가 없습니다.",
        "error1": "제목이 필요합니다.",
        "error2": "태그가 필요합니다.",
        "error3": "내보내기의 픽셀 크기는",
        "error4": "이 범위로 제한됩니다.",
        "error5": "올바른 숫자 값을 입력하세요.",
        "error6": "현재 이미지를 가져올 수 없습니다.",
        "thumbnailError": "사용 가능한 썸네일이 없습니다.",
        "advance": "고급 저장 옵션",
        "modeOption1": "포털에 저장",
        "modeOption2": "디스크에 저장",
        "default": "기본",
        "utm": "WGS84 UTM 구역",
        "layer": "레이어",
        "mercator": "WebMercatorAS",
        "folder": "폴더 선택"
    })
});