define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Salvestuskoht",
        "titleText": "Pealkiri (nõutav)",
        "description": "Kirjeldus",
        "tags": "Märksõnad (nõutavad)",
        "preview": "Eelvaade",
        "submit": "Salvesta",
        "cancel": "Loobu",
        "pixel": "Piksli suurus",
        "outsr": "Väljundi koordinaatsüsteem",
        "renderer": "TIFF-faili allalaadimise valikud",
        "formatText1": "Kuvatud kujul",
        "formatText2": "Toorandmed (kõik spektraalribad)",
        "extent": "Ulatuse määratlemiseks joonistage hulknurk",
        "drawText": "(alustamiseks klõpsake pilti)",
        "text": "Toorandmeid ei saa standardsetes fotovaaturites kuvada. Avage rakenduses ArcGIS Pro.",
        "error": "Kaardil ei ole nähtavaid pildikihte.",
        "error1": "Pealkiri on vajalik.",
        "error2": "Märksõnad on vajalikud.",
        "error3": "Ekspordi pikslisuurus on piiratud",
        "error4": "selle ulatuse korral.",
        "error5": "Sisestage sobiv arvväärtus.",
        "error6": "Teie pilti ei saa praegu eksportida.",
        "thumbnailError": "Pisipilt pole saadaval",
        "advance": "Täpsemad salvestusvalikud",
        "modeOption1": "Salvesta portaali",
        "modeOption2": "Salvesta kettale",
        "default": "Vaikimisi",
        "utm": "WGS84 UTM-tsoon",
        "layer": "Kiht",
        "mercator": "WebMercatorAS",
        "folder": "Vali kaust"
    })
});