define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Tallenna sijainti",
        "titleText": "Otsikko (pakollinen)",
        "description": "Kuvaus",
        "tags": "Tunnisteet (pakollinen)",
        "preview": "Esikatselu",
        "submit": "Tallenna",
        "cancel": "Peruuta",
        "pixel": "Pikselikoko",
        "outsr": "Tulosaineiston koordinaattijärjestelmä",
        "renderer": "TIFF-kuvan latausasetukset",
        "formatText1": "Näytetyssä muodossa",
        "formatText2": "Raaka-aineisto (kaikki kaistat)",
        "extent": "Määritä laajuus piirtämällä aluekohde",
        "drawText": "(aloita napsauttamalla kuvaa)",
        "text": "Raaka-aineistoa voi tarkastella vakiomuotoisilla valokuvien katseluohjelmilla. Avaa ArcGIS Prossa.",
        "error": "Kartassa ei ole näkyviä kuva-aineistokarttatasoja.",
        "error1": "Otsikko on pakollinen.",
        "error2": "Tunniste on pakollinen.",
        "error3": "Viennin pikselikoko on rajoitettu arvoon",
        "error4": "tämän laajuuden osalta.",
        "error5": "Anna kelvollinen numeroarvo.",
        "error6": "Kuvaasi ei voi viedä tällä kertaa.",
        "thumbnailError": "Pikkukuvaa ei käytettävissä",
        "advance": "Tallennuksen lisäasetukset",
        "modeOption1": "Tallenna portaaliin",
        "modeOption2": "Tallenna levylle",
        "default": "Oletusarvo",
        "utm": "WGS84 UTM -vyöhyke",
        "layer": "Karttataso",
        "mercator": "WebMercatorAS",
        "folder": "Valitse kansio"
    })
});