define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Position speichern",
        "titleText": "Titel (erforderlich)",
        "description": "Beschreibung",
        "tags": "Tags (erforderlich)",
        "preview": "Vorschau anzeigen",
        "submit": "Speichern",
        "cancel": "Abbrechen",
        "pixel": "Pixelgröße",
        "outsr": "Ausgabe-Raumbezug",
        "renderer": "Download-Optionen für TIFF-Dateien",
        "formatText1": "Wie angezeigt",
        "formatText2": "Rohdaten (alle Bänder)",
        "extent": "Zeichnen Sie ein Polygon, um die Ausdehnung zu definieren.",
        "drawText": "(zum Starten auf Bild klicken)",
        "text": "Die Rohdaten können nicht mit standardmäßigen Foto-Viewern angezeigt werden. Öffnen Sie diese mit ArcGIS Pro.",
        "error": "Keine sichtbaren Bilddaten-Layer auf der Karte.",
        "error1": "Titel ist erforderlich.",
        "error2": "Tags sind erforderlich.",
        "error3": "Die Pixelgröße des Exports ist beschränkt auf",
        "error4": "für diese Ausdehnung.",
        "error5": "Geben Sie einen gültigen numerischen Wert ein.",
        "error6": "Das Bild kann zurzeit nicht exportiert werden.",
        "thumbnailError": "Keine Miniaturansicht verfügbar",
        "advance": "Erweiterte Speicheroptionen",
        "modeOption1": "In Portal speichern",
        "modeOption2": "Auf Festplatte speichern",
        "default": "Standard",
        "utm": "WGS84-UTM-Zone",
        "layer": "Layer",
        "mercator": "WebMercatorAS",
        "folder": "Ordner auswählen"
    })
});