define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Uložit umístění",
        "titleText": "Název (povinné)",
        "description": "Popis",
        "tags": "Klíčová slova (povinné)",
        "preview": "Náhled",
        "submit": "Uložit",
        "cancel": "Storno",
        "pixel": "Velikost pixelu",
        "outsr": "Výstupní souřadnicový systém",
        "renderer": "Možnosti stahování souborů TIFF",
        "formatText1": "Dle zobrazení",
        "formatText2": "Surová data (všechna pásma)",
        "extent": "Nakreslete polygon a definujte tak rozsah.",
        "drawText": "(klikněte na snímek pro spuštění)",
        "text": "Surová data nelze zobrazit v běžných prohlížečích fotografií. Otevřít v ArcGIS Pro.",
        "error": "V mapě nejsou viditelné žádné vrstvy imagery.",
        "error1": "Je požadován název.",
        "error2": "Je požadován tag(tagy).",
        "error3": "Velikost pixelu pro export je omezena na",
        "error4": "pro tento rozsah.",
        "error5": "Zadejte platnou číselnou hodnotu.",
        "error6": "Váš snímek momentálně nelze exportovat.",
        "thumbnailError": "Miniatura není k dispozici",
        "advance": "Rozšířené možnosti ukládání",
        "modeOption1": "Uložit do portálu",
        "modeOption2": "Uložit na disk",
        "default": "výchozí",
        "utm": "Zóna UTM WGS84",
        "layer": "Vrstva",
        "mercator": "WebMercatorAS",
        "folder": "Vybrat složku"
    })
});