define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Simpan lokasi",
        "titleText": "Judul (wajib)",
        "description": "Deskripsi",
        "tags": "Tag (wajib)",
        "preview": "Pratinjau",
        "submit": "Simpan",
        "cancel": "Batalkan",
        "pixel": "Ukuran Piksel",
        "outsr": "Referensi Spasial Output",
        "renderer": "Opsi unduhan TIFF",
        "formatText1": "Sebagaimana ditampilkan",
        "formatText2": "Data mentah (semua pita)",
        "extent": "Gambar poligon untuk menentukan jangkauan",
        "drawText": "(klik gambar untuk memulai)",
        "text": "Data mentah tidak dapat ditampilkan dengan penampil foto standar. Buka dengan ArcGIS Pro.",
        "error": "Tidak ada layer gambar yang terlihat di peta.",
        "error1": "Judul diperlukan.",
        "error2": "Tag diperlukan.",
        "error3": "PixelSize ekspor dibatasi hingga",
        "error4": "untuk jangkauan ini.",
        "error5": "Harap masukkan nilai numerik yang valid.",
        "error6": "Gambar Anda kali ini tidak dapat diekspor.",
        "thumbnailError": "Tidak ada gambar mini tersedia",
        "advance": "Opsi simpan lanjutan",
        "modeOption1": "Simpan ke portal",
        "modeOption2": "Simpan ke disk",
        "default": "Default",
        "utm": "Zona WGS84 UTM",
        "layer": "Layer",
        "mercator": "WebMercatorAS",
        "folder": "Pilih folder"
    })
});