define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Enregistrer l’emplacement",
        "titleText": "Titre (obligatoire)",
        "description": "Description",
        "tags": "Balises (obligatoire)",
        "preview": "Aperçu",
        "submit": "Enregistrer",
        "cancel": "Annuler",
        "pixel": "Taille de pixel",
        "outsr": "Référence spatiale de sortie",
        "renderer": "Options de téléchargement TIFF",
        "formatText1": "Tel qu’à l’écran",
        "formatText2": "Données brutes (tous les canaux)",
        "extent": "Dessiner un polygone pour définir l’étendue",
        "drawText": "(cliquez sur une image pour démarrer)",
        "text": "Les données brutes ne peuvent pas s’afficher avec des visionneuses de photos standard. Ouvrez avec ArcGIS Pro.",
        "error": "Aucune couche d’imagerie visible sur la carte.",
        "error1": "Titre requis.",
        "error2": "Balise(s) requise(s).",
        "error3": "La taille de pixel de l’exportation est limitée à",
        "error4": "pour cette étendue.",
        "error5": "Saisissez une valeur numérique valide.",
        "error6": "Votre image ne peut actuellement pas être exportée.",
        "thumbnailError": "Aucune miniature disponible",
        "advance": "Options d’enregistrement avancées",
        "modeOption1": "Enregistrer sur le portail",
        "modeOption2": "Enregistrer sur le disque",
        "default": "Par défaut",
        "utm": "Zone UTM WGS84",
        "layer": "Couche",
        "mercator": "Web Mercator AS",
        "folder": "Sélectionner un dossier"
    })
});