define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Salvare locație",
        "titleText": "Titlu(obligatoriu)",
        "description": "Descriere",
        "tags": "Etichete(obligatorii)",
        "preview": "Previzualizare",
        "submit": "Salvare",
        "cancel": "Anulare",
        "pixel": "Dimensiune pixeli",
        "outsr": "Referință spațială de ieșire",
        "renderer": "Opțiuni descărcare TIFF",
        "formatText1": "Conform afișării",
        "formatText2": "Date brute(toate benzile)",
        "extent": "Trasați un poligon pentru a defini extinderea",
        "drawText": "(faceți clic pe imagine pentru a începe)",
        "text": "Datele brute nu pot fi afișate cu aplicații standard de vizualizare a fotografiilor. Deschideți cu ArcGIS Pro.",
        "error": "Niciun strat tematic imagistic vizibil pe hartă.",
        "error1": "Este necesar un titlu.",
        "error2": "Este necesară o etichetă (etichete).",
        "error3": "Dimensiunea pixelilor exportului este restricționată la",
        "error4": "pentru această extindere.",
        "error5": "Vă rugăm să introduceți o valoare numerică validă.",
        "error6": "Imaginea dvs. nu poate fi exportată în acest moment.",
        "thumbnailError": "Nicio miniatură nu este disponibilă",
        "advance": "Opțiuni de salvare avansate",
        "modeOption1": "Salvare pe portal",
        "modeOption2": "Salvare pe disc",
        "default": "Implicit",
        "utm": "Zona UTM WGS84",
        "layer": "Strat tematic",
        "mercator": "WebMercatorAS",
        "folder": "Selectaţi dosarul"
    })
});