define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Salvar localização",
        "titleText": "Título(exigido)",
        "description": "Descrição",
        "tags": "Tags(exigida)",
        "preview": "Visualizar",
        "submit": "Salvar",
        "cancel": "Cancelar",
        "pixel": "Tamanho do Pixel",
        "outsr": "Referência Espacial de Saída",
        "renderer": "Opções de download de TIFF",
        "formatText1": "Como exibido",
        "formatText2": "Dados brutos(todas as bandas)",
        "extent": "Desenhar polígono para definir a extensão",
        "drawText": "(clique na imagem para iniciar)",
        "text": "Os dados brutos não podem ser exibidos com visualizadores de fotos padrão. Abra com ArcGIS Pro.",
        "error": "Nenhuma camada de imagem visível no mapa.",
        "error1": "O título é necessário.",
        "error2": "Tags são exigidas.",
        "error3": "O Tamanho do Pixel de exportação é restrito a",
        "error4": "desta extensão.",
        "error5": "Insira um valor numérico válido.",
        "error6": "Sua imagem não pode ser exportada neste momento.",
        "thumbnailError": "Nenhuma miniatura disponível",
        "advance": "Opções avançadas para salvar",
        "modeOption1": "Salvar no portal",
        "modeOption2": "Salvar no disco",
        "default": "Padrão",
        "utm": "Zona WGS84 UTM",
        "layer": "Camada",
        "mercator": "WebMercatorAS",
        "folder": "Selecionar Pasta"
    })
});