define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Salva posizione",
        "titleText": "Titolo (obbligatorio)",
        "description": "Descrizione",
        "tags": "Tag (obbligatori)",
        "preview": "Anteprima",
        "submit": "Salva",
        "cancel": "Cancella",
        "pixel": "Dimensione pixel",
        "outsr": "Riferimento spaziale di output",
        "renderer": "Opzioni di download TIFF",
        "formatText1": "Come mostrato",
        "formatText2": "Dati grezzi (tutte le bande)",
        "extent": "Disegna poligono per definire l'estensione",
        "drawText": "(fai clic sull’immagine per iniziare)",
        "text": "I dati grezzi non possono essere visualizzati con dei visualizzatori di foto standard. Apri con ArcGIS Pro.",
        "error": "Nessun layer di immagine visibile nella mappa.",
        "error1": "Titolo obbligatorio.",
        "error2": "Tag obbligatori.",
        "error3": "PixelSize di esportazione è limitato a",
        "error4": "per questa estensione.",
        "error5": "Immettere un valore numerico valido.",
        "error6": "L’immagine non può essere esportata al momento.",
        "thumbnailError": "Nessuna anteprima disponibile",
        "advance": "Opzioni di salvataggio avanzate",
        "modeOption1": "Salva sul portale",
        "modeOption2": "Salva sul disco",
        "default": "Predefinito",
        "utm": "Zona UTM WGS84",
        "layer": "Layer",
        "mercator": "WebMercatorAS",
        "folder": "Seleziona cartella"
    })
});