define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Spremi lokaciju",
        "titleText": "Naslov (obavezno)",
        "description": "Opis",
        "tags": "Oznake (obavezno)",
        "preview": "Pretpregled",
        "submit": "Spremi",
        "cancel": "Odustani",
        "pixel": "Veličina piksela",
        "outsr": "Izvoz prostorne reference",
        "renderer": "Opcije preuzimanja TIFF-a",
        "formatText1": "Kao što je prikazano",
        "formatText2": "Neobrađeni podaci (svi kanali)",
        "extent": "Nacrtajte poligon za definiranje obuhvata",
        "drawText": "(kliknite na sliku za početak)",
        "text": "Neobrađeni podaci ne mogu se prikazati sa standardnim preglednicima fotografija. Otvori s ArcGIS Pro.",
        "error": "Nema vidljivih slojeva slika na karti.",
        "error1": "Potreban je naslov.",
        "error2": "Potrebne su oznake.",
        "error3": "Veličina piksela za izvoz ograničena je na",
        "error4": "za ovaj obuhvat.",
        "error5": "Unesite valjanu brojčanu vrijednost.",
        "error6": "Vaša se slika trenutno ne može izvesti.",
        "thumbnailError": "Nema dostupnih sličica",
        "advance": "Napredne opcije spremanja",
        "modeOption1": "Spremi na portal",
        "modeOption2": "Spremi na disk",
        "default": "Zadano",
        "utm": "Zona WGS84 UTM",
        "layer": "Sloj",
        "mercator": "WebMercatorAS",
        "folder": "Odaberi mapu"
    })
});