define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Zapisz lokalizację",
        "titleText": "Tytuł (wymagany)",
        "description": "Opis",
        "tags": "Znaczniki (wymagane)",
        "preview": "Podgląd",
        "submit": "Zapisz",
        "cancel": "Anuluj",
        "pixel": "Rozmiar pikseli",
        "outsr": "Wynikowe odniesienie przestrzenne",
        "renderer": "Opcje pobierania obrazu TIFF",
        "formatText1": "Tak, jak jest wyświetlany",
        "formatText2": "Surowe dane (wszystkie pasma)",
        "extent": "Narysuj poligon, aby zdefiniować zasięg",
        "drawText": "(kliknij obraz, aby rozpocząć)",
        "text": "Surowych danych nie można wyświetlać w standardowych aplikacjach do przeglądania zdjęć. Otwórz w aplikacji ArcGIS Pro.",
        "error": "Brak widocznych warstw zobrazowań na mapie.",
        "error1": "Tytuł jest wymagany.",
        "error2": "Znacznik/znaczniki są wymagane.",
        "error3": "Parametr PixelSize eksportu jest ograniczony do",
        "error4": "dla tego zasięgu.",
        "error5": "Wpisz prawidłową wartość liczbową.",
        "error6": "W tej chwili nie można wyeksportować Twojego obrazu.",
        "thumbnailError": "Brak dostępnej miniatury",
        "advance": "Zaawansowane opcje zapisu",
        "modeOption1": "Zapisz w portalu",
        "modeOption2": "Zapisz na dysku",
        "default": "Domyślnie",
        "utm": "Strefa WGS84 UTM",
        "layer": "Warstwa",
        "mercator": "WebMercatorAS",
        "folder": "Wybierz folder"
    })
});