define({
    root: ({
        _widgetLabel: "IS ImageExport",
        mode: "Save location",
        titleText: "Title(required)",
        description: "Description",
        tags: "Tags(required)",
        preview: "Preview",
        submit: "Save",
        cancel: "Cancel",
        pixel: "Pixel Size",
        outsr: "Output Spatial Reference",
        renderer: "TIFF download options",
        formatText1: "As displayed",
        formatText2: "Raw data(all bands)",
        extent: "Draw polygon to define extent",
        drawText: "(click image to start)",
        text: "The raw data can't be displayed with standard photo viewers. Open with ArcGIS Pro.",
        error: "No visible imagery layers on the map.",
        error1: "Title is required.",
        error2: "Tag(s) is required.",
        error3: "PixelSize of export is restricted to",
        error4: "for this extent.",
        error5: "Please enter a valid numeric value.",
        error6: "Your image can't be exported at this time.",
        thumbnailError: "No thumbnail available",
        advance: "Advanced save options",
        modeOption1: "Save to portal",
        modeOption2: "Save to disk",
        default: "Default",
        utm: "WGS84 UTM Zone",
        layer: "Layer",
        mercator: "WebMercatorAS",
        folder: "Select folder"
    }),
    "ar": 1,
    "bs": 1,
    "ca": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hi": 1,
    "hr": 1,
    "hu": 1,
    "id": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sl": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});
