define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "שמור מיקום",
        "titleText": "כותרת (נדרשת)",
        "description": "תאור",
        "tags": "תגים (נדרשים)",
        "preview": "תצוגה מקדימה",
        "submit": "שמירה",
        "cancel": "בטל",
        "pixel": "גודל פיקסל",
        "outsr": "יחוס מרחבי לנתוני הפלט",
        "renderer": "אפשרויות הורדת TIFF",
        "formatText1": "כפי שמוצג",
        "formatText2": "נתונים גולמיים (כל הערוצים)",
        "extent": "צייר פוליגון כדי להגדיר את התיחום",
        "drawText": "(לחץ על תצלום כדי להתחיל)",
        "text": "לא ניתן להציג נתונים גולמיים במציגי תמונות סטנדרטיים. פתח ב-ArcGIS Pro.",
        "error": "אין שכבות גלויות של תצלומים במפה.",
        "error1": "הכותרת היא שדה חובה.",
        "error2": "התגים נדרשים.",
        "error3": "הערך PixelSize של הייצוא מוגבל ל-",
        "error4": "עבור תיחום זה.",
        "error5": "הזן ערך מספרי חוקי.",
        "error6": "לא ניתן לייצא את התצלום שלך כעת.",
        "thumbnailError": "אין תמונה ממוזערת זמינה",
        "advance": "אפשרויות שמירה מתקדמות",
        "modeOption1": "שמור בפורטל",
        "modeOption2": "שמור בדיסק",
        "default": "ברירת מחדל",
        "utm": "אזור WGS84 UTM",
        "layer": "שכבה",
        "mercator": "WebMercatorAS",
        "folder": "בחר תיקייה"
    })
});