/*
 | Copyright 2018 Esri. All Rights Reserved.
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */
define({
    root: ({
        _widgetLabel: "IS ImageViewer",
        layer: "Sensor",
        rendering: "Rendering",
        searchImages: "Search for individual images",
        searchRange: "Search range",
        days: "Day(s)",
        weeks: "Week(s)",
        months: "Month(s)",
        years: "Year(s)",
        show: "Show",
        image: "Image",
        footprint: "Footprint",
        leftImage: "Default Layer",
        rightImage: "Comparison Layer",
        dropDown: "Show images in drop down list.",
        enableSearchImages: "Enable to search for specific images.",
        refreshQuery: "Refresh query based on current extent.",
        zoomIn: "Zoom in to select images.",
        fieldNotSpec: "Field is not specified.",
        noObject: "No OBJECTID field.",
        noCategory: "No Category field.",
        serviceError: "Services pre 10.2.1 not supported.",        
        slider: "Show images on slider.",
        images: "image(s)",
        dates: "Date",
        footprintMessage: "Number of footprints selected exceed 20. Only first 20 will be displayed. Press OK not to warn again.",        
        noScenes: "No scenes in current extent.",
		leftRightIdentical: "Left and Right Image are identical.",
		imageryOperation: "What do you want to do?",
		defaultLabel: "Select an optional tool",
		tool1: "Create a mask",
		tool2: "Explore spectral profiles",
        tool3: "Create spectral scatterplot",
        tool0: "Explore temporal profiles",
        sentinelTemporal: "Sign in to access Sentinel-2 temporally",

		
    
     
        zoom: "Zoom in to select images.",
        primary: "Primary Image",
        comparison: "Comparison Image",
        method: "Method",
        apply: "Apply",
        clear: "Clear",
        nir: "Infrared Band",
        red: "Red Band",
        green: "Green Band",
        swir: "Short-wave Infrared Band",
        band1: "Band A",
        band2: "Band B",
 
        method1: "Image brightness",
        method2: "Vegetation Index",
        method3: "Soil Adjusted Veg. Index",
        method4: "Water Index",
        method5: "Burn Index",
        method6: "Less than my threshold",
        method7: "Greater than my threshold",
        method8: "Single Band",
        method9: "Custom Index",
        dropDown: "Show images in drop down list.",
        transparency: "Transparency(results)",
        slider: "Show images on slider.",
        error1: "Field is not specified.",
        error2: "No OBJECTID field.",
        error3: "No Category field.",
        error4: "Cannot perform action for layer.",
        error5: "Services pre 10.2.1 not supported.",
        error6: "No scenes in current extent.",
        error7: "Please select two different images.",
        indexText: "Advanced index options",
        date: "Date",
        areaText3: "Area Covered",
        unit: "km",
        imageLabel: "image(s)",
        extent: "Draw polygon(s) to define extent",
        colorPicker: "Color Picker",
        refresh: "Refresh Button",
        refreshTooltip: "Refresh the image list based on the current extent.",
        colorpickerText: "Choose a color for your mask",
        sliderText: "Set your threshold",
        maskModeText: "Which values should I mask?",
        positiveSliderText: "Set the minimum increase required between the images before the area is shown in green.",
        negativeSliderText: "Set the minimum decrease required between the images before the area is shown in magenta.",
        updateResult: "Your image has changed. Click Apply to update analysis."

    }),
    "ar": 1,
	"bs": 1,
	"ca": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"hi": 1,
	"hr": 1,
	"hu": 1,
	"id": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sl": 1,
	"sr": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1,
	"zh-tw": 1
});
