define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Lagre lokasjon",
        "titleText": "Tittel(påkrevd)",
        "description": "Beskrivelse",
        "tags": "Merker(påkrevd)",
        "preview": "Forhåndsvisning",
        "submit": "Lagre",
        "cancel": "Avbryt",
        "pixel": "Pikselstørrelse",
        "outsr": "Romlig referanse for utdata",
        "renderer": "Alternativer for TIFF-nedlasting",
        "formatText1": "Som vist",
        "formatText2": "Rådata(alle bånd)",
        "extent": "Tegn polygon for å definere utstrekning",
        "drawText": "(klikk på bildet for å starte)",
        "text": "Rådataene kan ikke vises på standard bildevisere. Åpne med ArcGIS Pro.",
        "error": "Ingen synlige bildelag på kartet.",
        "error1": "Du må fylle ut tittel.",
        "error2": "Merke(r) er påkrevd.",
        "error3": "Pikselstørrelse for eksport er begrenset til",
        "error4": "for denne utstrekningen.",
        "error5": "Angi en gyldig numerisk verdi.",
        "error6": "Bildet kan ikke eksporteres nå.",
        "thumbnailError": "Ingen tilgjengelige miniatyrbilder",
        "advance": "Avanserte lagringsalternativer",
        "modeOption1": "Lagre på portalen",
        "modeOption2": "Lagre på disk",
        "default": "Standard",
        "utm": "WGS84 UTM-sone",
        "layer": "Lag",
        "mercator": "WebMercatorAS",
        "folder": "Velg mappe"
    })
});