define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Locatie opslaan",
        "titleText": "Titel (vereist)",
        "description": "Beschrijving",
        "tags": "Tags (vereist)",
        "preview": "Voorbeeld",
        "submit": "Opslaan",
        "cancel": "Afbreken",
        "pixel": "Pixelgrootte",
        "outsr": "Uitvoer ruimtelijke referentie",
        "renderer": "Downloadopties TIFF",
        "formatText1": "Als weergegeven",
        "formatText2": "Raw data (alle banden)",
        "extent": "Teken polygoon om de extent te bepalen",
        "drawText": "(op afbeelding klikken om te beginnen)",
        "text": "De raw data kunnen niet worden weergegeven met de standaard foto-viewers. Openen met ArcGIS Pro.",
        "error": "Geen zichtbare satellietbeeldlagen op de kaart.",
        "error1": "Titel is vereist.",
        "error2": "Tag(s) is verplicht.",
        "error3": "PixelSize van export is beperkt tot",
        "error4": "voor deze extent.",
        "error5": "Voer een geldige numerieke waarde in.",
        "error6": "Uw afbeelding kan nu niet worden geëxporteerd.",
        "thumbnailError": "Geen thumbnail beschikbaar",
        "advance": "Geavanceerde opties voor opslaan",
        "modeOption1": "Opslaan naar portaal",
        "modeOption2": "Opslaan op schijf",
        "default": "Standaard",
        "utm": "WGS84 UTM Zone",
        "layer": "Kaartlaag",
        "mercator": "WebMercatorAS",
        "folder": "Selecteer map"
    })
});