define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Guardar localização",
        "titleText": "Título (obrigatório)",
        "description": "Descrição",
        "tags": "Palavras-chave(obrigatórias)",
        "preview": "Pré-visualizar",
        "submit": "Guardar",
        "cancel": "Cancelar",
        "pixel": "Tamanho de Pixeis",
        "outsr": "Referência Espacial de Saída",
        "renderer": "Opções de transferência TIFF",
        "formatText1": "Como exibido",
        "formatText2": "Dados raw(todas as bandas)",
        "extent": "Desenhar polígono para definir extensão",
        "drawText": "(clique na imagem para iniciar)",
        "text": "Os dados raw não podem ser exibidos com visualizadores de fotos padrão. Abrir com o ArcGIS Pro.",
        "error": "Não existem camadas de imagens visíveis no mapa.",
        "error1": "O Título é obrigatório.",
        "error2": "Palavra(s) Chave são obrigatórias.",
        "error3": "PixelSize de exportar encontra-se restrito a",
        "error4": "para esta extensão.",
        "error5": "Por favor, introduza um valor numérico válido.",
        "error6": "Não é possível exportar a sua imagem de momento.",
        "thumbnailError": "Nenhuma miniatura disponível",
        "advance": "Opções avançadas para guardar",
        "modeOption1": "Guardar no portal",
        "modeOption2": "Guardar no disco",
        "default": "Padrão",
        "utm": "Zona WGS84 UTM",
        "layer": "Camada",
        "mercator": "WebMercatorAS",
        "folder": "Selecionar pasta"
    })
});