define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Įrašyti vietą",
        "titleText": "Antraštė (būtina)",
        "description": "Aprašymas",
        "tags": "Raktažodžiai (būtini).",
        "preview": "Peržiūra",
        "submit": "Išsaugoti",
        "cancel": "Atšaukti",
        "pixel": "Pikselių dydis",
        "outsr": "Išvesties koordinačių sistema",
        "renderer": "TIFF atsisiuntimo parinktys",
        "formatText1": "Kaip parodyta",
        "formatText2": "Neapdoroti duomenys (visi kanalai)",
        "extent": "Brėžkite aprėpties poligoną",
        "drawText": "(paspauskite vaizdą norėdami pradėti)",
        "text": "Standartinės nuotraukų peržiūros priemonės negali rodyti neapdorotų duomenų. Atverti naudojant ArcGIS Pro",
        "error": "Žemėlapyje matomų atvaizdų sluoksnių nėra.",
        "error1": "Būtinas pavadinimas.",
        "error2": "Būtinas raktažodis (-iai).",
        "error3": "Eksportuoto failo dydis pikseliais apribotas",
        "error4": "šiai aprėpčiai.",
        "error5": "Įveskite leistiną skaitinę reikšmę.",
        "error6": "Šiuo metu jūsų vaizdo eksportuoti neįmanoma.",
        "thumbnailError": "Nėra miniatiūros",
        "advance": "Išplėstinės įrašymo parinktys",
        "modeOption1": "Įrašyti į portalą",
        "modeOption2": "Įrašyti į diską",
        "default": "Numatytas",
        "utm": "WGS84 UTM zona",
        "layer": "Sluoksnis",
        "mercator": "WebMercatorAS",
        "folder": "Pasirinkti aplanką"
    })
});