define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Shrani lokacijo",
        "titleText": "Ime (zahtevano)",
        "description": "Opis",
        "tags": "Oznake (zahtevano)",
        "preview": "Predogled",
        "submit": "Shrani",
        "cancel": "Prekliči",
        "pixel": "Velikost pikslov",
        "outsr": "Izhodni koordinatni sistem",
        "renderer": "Možnosti prenosa TIFF",
        "formatText1": "Kot je prikazano",
        "formatText2": "Neobdelani podatki (vsi pasovi)",
        "extent": "Nariši poligon za določanje obsega",
        "drawText": "(kliknite sliko za začetek)",
        "text": "Neobdelanih podatkov ni mogoče prikazati s standardnimi pregledovalniki slik. Odpri z ArcGIS Pro.",
        "error": "Na karti ni vidnih slikovnih slojev.",
        "error1": "Zahtevano je ime.",
        "error2": "Zahtevane so oznake.",
        "error3": "PixelSize izvoza je omejen na",
        "error4": "za ta obseg.",
        "error5": "Vnesite veljavno številsko vrednost.",
        "error6": "Vaše slike trenutno ni mogoče izvoziti.",
        "thumbnailError": "Sličica ni na voljo",
        "advance": "Napredne možnosti shranjevanja",
        "modeOption1": "Shrani na portal",
        "modeOption2": "Shrani na disk",
        "default": "Privzeto",
        "utm": "WGS84 UTM cona",
        "layer": "Sloj",
        "mercator": "WebMercatorAS",
        "folder": "Izberi mapo"
    })
});