define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Guardar ubicación",
        "titleText": "Título (obligatorio)",
        "description": "Descripción",
        "tags": "Etiquetas (obligatorias)",
        "preview": "Previsualización",
        "submit": "Guardar",
        "cancel": "Cancelar",
        "pixel": "Tamaño de píxel",
        "outsr": "Referencia espacial de salida",
        "renderer": "Opciones de descarga de TIFF",
        "formatText1": "Como se muestra",
        "formatText2": "Datos sin procesar (todas las bandas)",
        "extent": "Dibujar polígono para definir la extensión",
        "drawText": "(haga clic en la imagen para empezar)",
        "text": "No es posible mostrar los datos sin procesar con visores de imágenes estándar. Abrir con ArcGIS Pro.",
        "error": "No hay capas de imágenes visibles en el mapa.",
        "error1": "Se requiere un título.",
        "error2": "Se requieren una o varias etiquetas.",
        "error3": "Valor PixelSize de la exportación restringido a",
        "error4": "para esta extensión.",
        "error5": "Introduzca un valor numérico válido.",
        "error6": "No es posible exportar su imagen en estos momentos.",
        "thumbnailError": "Vista en miniatura no disponible",
        "advance": "Opciones avanzadas de guardado",
        "modeOption1": "Guardar en el portal",
        "modeOption2": "Guardar en el disco",
        "default": "Predeterminado",
        "utm": "Zona UTM WGS84",
        "layer": "Capa",
        "mercator": "WebMercatorAS",
        "folder": "Seleccionar carpeta"
    })
});