define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Sačuvaj lokaciju",
        "titleText": "Naslov (obavezno)",
        "description": "Opis",
        "tags": "Oznake (obavezno)",
        "preview": "Prikaži",
        "submit": "Sačuvaj",
        "cancel": "Otkaži",
        "pixel": "Veličina piksela",
        "outsr": "Izlazna prostorna referenca",
        "renderer": "Opcije za TIFF preuzimanje",
        "formatText1": "Kao što je prikazano",
        "formatText2": "Sirovi podaci (svi opsezi)",
        "extent": "Nacrtajte poligon za definisanje obuhvata",
        "drawText": "(kliknite na sliku da biste započeli)",
        "text": "Sirovi podaci ne mogu da se prikažu pomoću standardnih pregledača slika. Otvorite pomoću ArcGIS Pro.",
        "error": "Na mapi nema vidljivih slojeva snimka.",
        "error1": "Naslov je obavezan.",
        "error2": "Oznaka/oznake je/su obavezni.",
        "error3": "Veličina piksela izvoza je ograničena na",
        "error4": "za ovaj obuhvat.",
        "error5": "Unesite važeću numeričku vrednost.",
        "error6": "Trenutno nije moguće izvesti sliku.",
        "thumbnailError": "Nema dostupnih sličica",
        "advance": "Napredne opcije čuvanja",
        "modeOption1": "Sačuvaj na portal",
        "modeOption2": "Sačuvaj na disk",
        "default": "Podrazumevano",
        "utm": "WGS84 UTM Zone",
        "layer": "Sloj",
        "mercator": "WebMercatorAS",
        "folder": "Selektujte fasciklu"
    })
});