define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "保存位置",
        "titleText": "标题(必填项)",
        "description": "描述",
        "tags": "标签(必填项)",
        "preview": "预览",
        "submit": "保存",
        "cancel": "取消",
        "pixel": "像素大小",
        "outsr": "输出空间参考",
        "renderer": "TIFF 下载选项",
        "formatText1": "如显示",
        "formatText2": "原始数据(所有波段)",
        "extent": "绘制用于定义范围的面",
        "drawText": "(单击影像以开始)",
        "text": "标准照片查看器无法显示原始数据。 使用 ArcGIS Pro 打开。",
        "error": "地图中没有可见的影像图层。",
        "error1": "标题为必填项。",
        "error2": "标签(一个或多个)为必填项。",
        "error3": "导出内容的像素大小限制为",
        "error4": "针对此范围。",
        "error5": "请输入有效的数值。",
        "error6": "此时无法导出影像。",
        "thumbnailError": "无可用缩略图",
        "advance": "高级保存选项。",
        "modeOption1": "保存到门户",
        "modeOption2": "保存到磁盘",
        "default": "默认",
        "utm": "WGS84 UTM 带",
        "layer": "图层",
        "mercator": "WebMercatorAS",
        "folder": "选择文件夹"
    })
});