define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Saglabāt novietojumu",
        "titleText": "Virsraksts (obligāti)",
        "description": "Apraksts",
        "tags": "Atslēgas vārdi (obligāti)",
        "preview": "Priekšskatījums",
        "submit": "Saglabāt",
        "cancel": "Atcelt",
        "pixel": "Pikseļu izmērs",
        "outsr": "Izvades telpiskā atskaite",
        "renderer": "TIFF lejupielādes opcijas",
        "formatText1": "Kā attēlots",
        "formatText2": "Neapstrādāti dati (visi kanāli)",
        "extent": "Zīmēt daudzstūri, lai noteiktu pārklājumu",
        "drawText": "(noklikšķiniet uz attēla, lai sāktu)",
        "text": "Neapstrādātus datus var parādīt ar standarta fotoattēlu skatītājiem. Atvērt ar ArcGIS Pro",
        "error": "Kartē nav redzamu attēlu slāņu.",
        "error1": "Nosaukums jānorāda obligāti.",
        "error2": "Atslēgas vārds(-i) jānorāda obligāti.",
        "error3": "Eksporta PixelSize ir ierobežots",
        "error4": "šajā apjomā.",
        "error5": "Ievadiet derīgu skaitlisku vērtību.",
        "error6": "Jūsu attēlu šoreiz nevar eksportēt.",
        "thumbnailError": "Nav pieejams neviens sīktēls",
        "advance": "Uzlabotās saglabāšanas opcijas",
        "modeOption1": "Saglabāt portālā",
        "modeOption2": "Saglabāt diskā",
        "default": "Noklusējums",
        "utm": "WGS84 UTM zona",
        "layer": "Slānis",
        "mercator": "WebMercatorAS",
        "folder": "Izvēlēties mapi"
    })
});