define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Spara plats",
        "titleText": "Titel (obligatoriskt)",
        "description": "Beskrivning",
        "tags": "Taggar (obligatoriskt)",
        "preview": "Förhandsgranska",
        "submit": "Spara",
        "cancel": "Avbryt",
        "pixel": "Pixelstorlek",
        "outsr": "Geografisk referens för utdata",
        "renderer": "Hämtningsalternativ för TIFF",
        "formatText1": "Som visas",
        "formatText2": "Rådata (alla band)",
        "extent": "Rita polygon för att definiera utbredning",
        "drawText": "(klicka på bilden för att starta)",
        "text": "Rådata kan inte visas med standardbildvisare. Öppna med ArcGIS Pro.",
        "error": "Inga synliga bildlager i kartan.",
        "error1": "Titel krävs.",
        "error2": "Tagg(ar) krävs.",
        "error3": "Pixelstorleken i exporten begränsas till",
        "error4": "för denna utbredning.",
        "error5": "Ange ett giltigt numeriskt värde.",
        "error6": "Bilden kan inte exporteras för närvarande.",
        "thumbnailError": "Ingen miniatyrbild finns tillgänglig",
        "advance": "Avancerade alternativ för att spara",
        "modeOption1": "Spara i portal",
        "modeOption2": "Spara på disk",
        "default": "Standard",
        "utm": "WGS84 UTM-zon",
        "layer": "Lager",
        "mercator": "WebMercatorAS",
        "folder": "Välj mapp"
    })
});