define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "儲存位置",
        "titleText": "標題 (必填項)",
        "description": "描述",
        "tags": "標記 (必填項)",
        "preview": "預覽",
        "submit": "儲存",
        "cancel": "取消",
        "pixel": "像素大小",
        "outsr": "輸出空間參考",
        "renderer": "TIFF 下載選項",
        "formatText1": "如圖所示",
        "formatText2": "原生資料 (所有頻帶)",
        "extent": "繪製多邊形以定義範圍",
        "drawText": "(按一下圖片以開始)",
        "text": "無法使用標準相片檢視器來顯示原生資料。 使用 ArcGIS Pro 開啟。",
        "error": "地圖上沒有可見的影像圖層。",
        "error1": "標題為必填項。",
        "error2": "標記為必填項。",
        "error3": "匯出的 PixelSize 限制",
        "error4": "此範圍。",
        "error5": "請輸入有效的數值。",
        "error6": "目前無法匯出您的圖片。",
        "thumbnailError": "無可用的縮圖",
        "advance": "進階儲存選項",
        "modeOption1": "儲存到入口網站",
        "modeOption2": "儲存到磁碟",
        "default": "預設",
        "utm": "WGS84 UTM 區域",
        "layer": "圖層",
        "mercator": "WebMercatorAS",
        "folder": "選擇資料夾"
    })
});