define({
    root: ({
        _widgetLabel: "IS ImageExport",
        "mode": "Konumu kaydet",
        "titleText": "Başlık (gerekli)",
        "description": "Açıklama",
        "tags": "Etiketler (gerekli)",
        "preview": "Önizleme",
        "submit": "Kaydet",
        "cancel": "İptal Et",
        "pixel": "Piksel Boyutu",
        "outsr": "Çıktı Mekansal Referansı",
        "renderer": "TIFF indirme seçenekleri",
        "formatText1": "Görüntülendiği gibi",
        "formatText2": "Ham veriler (tüm gruplar)",
        "extent": "Kapsamı tanımlamak için çokgen çizin",
        "drawText": "(başlamak için görüntüye tıklayın)",
        "text": "Ham veriler standart fotoğraf görüntüleyicileriyle görüntülenemez. ArcGIS Pro ile aç.",
        "error": "Haritada görünür görüntü katmanı yok.",
        "error1": "Başlık gerekli.",
        "error2": "Etiket gerekli.",
        "error3": "Aktarım için maksimum Piksel Boyutu",
        "error4": "bu yayılım için.",
        "error5": "Geçerli bir sayısal değer girin.",
        "error6": "Görüntünüz şu anda dışa aktarılamıyor.",
        "thumbnailError": "Kullanılabilir küçük resim yok",
        "advance": "Gelişmiş kaydetme seçenekleri",
        "modeOption1": "Portala kaydet",
        "modeOption2": "Diske kaydet",
        "default": "Varsayılan",
        "utm": "WGS84 UTM Zone",
        "layer": "Katman",
        "mercator": "WebMercatorAS",
        "folder": "Klasör seç"
    })
});